### ISSUE TITLE
Leichter Einstieg...

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/twoeg#1]
Hey Thomas,

wäre es evtl. möglich einen REX-Export mit einem recht einfachen Beispiel der Verwendung von twÖg zur Verfügung zu stellen?

Es fällt dann bestimmt leichte einen Einstieg zu finden (zumindest mir :-))

LG
Oliver

**Comment by tgoellner** [comment]
Hallo Oliver,

in der Readme-Datei findet sich ein Beispiel - das Addon lässt sich im 
Frontend und im Backend innerhalb von <?php ?> Tags verwenden.

Grüße,
Thomas.

Am 16.06.16 um 13:23 schrieb Oliver Kreischer:

> Hey Thomas,
> 
> wäre es evtl. möglich einen REX-Export mit einem recht einfachen
> Beispiel der Verwendung von twÖg zur Verfügung zu stellen?
> 
> Es fällt dann bestimmt leichte einen Einstieg zu finden (zumindest mir :-))
> 
> LG
> Oliver
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/FriendsOfREDAXO/twoeg/issues/1, or mute the thread
> https://github.com/notifications/unsubscribe/AB7rOLTTi3wn2SQLCZqx23VFnj1v_juLks5qMTIpgaJpZM4I3SM3.

## 

........................................
GÖLLNER - Digitale Medien

Thomas Göllner
Böttcherstraße 3 - 28195 Bremen

Telefon: +49 421 322 72 02
Telefax: +49 421 322 72 09
Skype: tgoellner
Web: www.thomasgoellner.de

**Comment by olien** [comment]
Danke!
